### ISSUE TITLE
There is no register 'pretrain_encoder'?

### ISSUE THREAD

**Issue by HEQINGZHAO** [zhouc20/LatentGraphDiffusion#3]
train_dict[cfg.train.mode](loggers, loaders, model, optimizer,scheduler)
 KeyError: 'pretrain_encoder'

**Comment by zhouc20** [comment]
'pretrain_encoder' is registered in line 236 of lgd/train/pretrain_encoder.py - have you organized everything as in the repo?

**Comment by HEQINGZHAO** [comment]
Thank you for your response, the issue has been resolved!
