### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by CalmaQi** [zhouc20/LatentGraphDiffusion#4]
Great job, but I've always been unsure about which parameters to add to the cfg file. Could you please provide a valid config YAML that I can use to run the code directly?

**Comment by zhouc20** [comment]
All yaml files in /cfg/ are valid; you can also change the file path of the checkpoint of the autoencoder in diffusion.first_stage_config in the stage of training diffusion

**Comment by CalmaQi** [comment]
Thank you for your response.I keep encountering errors when running the project code,mainly because many parameters in the configuration&nbsp; not set, and Im not clear on how to set them,such as errors related to cfg.name_tag being missing. Have you ever run the code with this github project?




---Original---
From: "Cai ***@***.***&gt;
Date: Sat, Nov 23, 2024 06:14 AM
To: ***@***.***&gt;;
Cc: "JiaQi ***@***.******@***.***&gt;;
Subject: Re: [zhouc20/LatentGraphDiffusion] AttributeError (Issue #4)




 
All yaml files in /cfg/ are valid; you can also change the file path of the checkpoint of the autoencoder in diffusion.first_stage_config in the stage of training diffusion

**Comment by zhouc20** [comment]
I ran the code and did not encounter such errors. cfg.name_tag is overwritten by default in line 25 of /lgd/configs/defaults_config.py - have you organized all the files as in the repo? If you keep having this error, just specify the name with whatever you want in the yaml file or /lgd/configs/defaults_config.py

**Comment by CalmaQi** [comment]
Thank you very much for your reply. I see that there are indeed many py files that have registered parameters, but I am now suspecting that it might be because my environment torch.geometric is not properly registered. Could you please provide the specific versions of all the pip packages? Thank you very much.






---Original---
From: "Cai ***@***.***&gt;
Date: Sat, Nov 23, 2024 10:07 AM
To: ***@***.***&gt;;
Cc: "JiaQi ***@***.******@***.***&gt;;
Subject: Re: [zhouc20/LatentGraphDiffusion] AttributeError (Issue #4)




 
I ran the code and did not encounter such errors. cfg.name_tag is overwritten by default in line 25 of /lgd/configs/defaults_config.py - have you organized all the files as in the repo? If you keep having this error, just specify the name with whatever you want in the yaml file or /lgd/configs/defaults_config.py

**Comment by CalmaQi** [comment]
thanks，I have solved it.

**Comment by TalentedMUSE** [comment]
> thanks，I have solved it.

Could you tell me how to solve this problem? I tried many times but still encountered this AttributeError. Many thanks!

**Comment by CalmaQi** [comment]
> > thanks，I have solved it.
> 
> Could you tell me how to solve this problem? I tried many times but still encountered this AttributeError. Many thanks!

Suggest taking a look at the GraphGPS repository, and you need to create a new init.py file to import it, in order to ensure that the register_network class is successful.

**Comment by TalentedMUSE** [comment]
> > > thanks，I have solved it.
> > 
> > 
> > Could you tell me how to solve this problem? I tried many times but still encountered this AttributeError. Many thanks!
> 
> Suggest taking a look at the GraphGPS repository, and you need to create a new init.py file to import it, in order to ensure that the register_network class is successful.

Thanks a lot! I finally solved it.
