### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by zzrs123** [zhouc20/LatentGraphDiffusion#7]
**The work is indeed done very well, but it has to be said that the cfg of the code is very confusing. It seems that default_cfg is not running correctly. I also encountered the problem of name_tag, and for example, the run_cultiple_stplits property is not set.**

**Comment by zzrs123** [comment]
Perhaps I should delve deeper into the source code or reproduce GraphGPS first.

**Comment by zhouc20** [comment]
It is possibly because the version of pyg. You can follow the environment setup instructions of GraphGPS.
